### ISSUE TITLE
Batch insert with 30 or more columns causes SQLException: Not all parameters binded

### ISSUE THREAD

**Issue by greysap** [yandex/clickhouse-jdbc#106]
Hi! 
I get this exception, when 30 or more columns passed with batch insert:
```
java.sql.SQLException: Not all parameters binded
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.checkBinded(ClickHousePreparedStatementImpl.java:120)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.buildBinds(ClickHousePreparedStatementImpl.java:126)
	at ru.yandex.clickhouse.ClickHousePreparedStatementImpl.addBatch(ClickHousePreparedStatementImpl.java:327)
	at org.easybatch.jdbc.JdbcRecordWriter.writeRecords(JdbcRecordWriter.java:86)
	at org.easybatch.core.job.BatchJob.writeBatch(BatchJob.java:203)
	at org.easybatch.core.job.BatchJob.call(BatchJob.java:79)
	at org.easybatch.core.job.BatchJob.call(BatchJob.java:22)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

Example code - https://github.com/greysap/randombatch2clickhouse/blob/master/src/main/java/house/greysap/App.java
This code will work after commenting lines 74, 186 and 298 (i.e. lowering columns number from 30 to 29).

What's the best way to insert batch with many columns via JDBC driver?

**Comment by serebrserg** [comment]
Hello.
Here is the test showing that 30 columns makes no problem for jdbc driver (it works).
There are many things going on in your example like JdbcRecordWriter and properties provider. There may be some restrictions in them.
If it is not, and the problem is indeed in the driver, could you provide the test case with direct use of jdbc api?

```java
@Test
    public void test40() throws SQLException {
        int fieldsNum = 40;
        int rowsNum = 10;
        connection.createStatement().execute("DROP TABLE IF EXISTS test.test_40");
        List<String> fieldsDesc = new ArrayList<String>();
        List<String> fields = new ArrayList<String>();
        List<String> questions = new ArrayList<String>();
        for (int i = 0; i < fieldsNum; i++) {
            fieldsDesc.add("field" + i + " UInt32");
            fields.add("field" + i);
            questions.add("?");
        }
        connection.createStatement().execute(
                "CREATE TABLE IF NOT EXISTS test.test_40 (" + Joiner.on(",").join(fieldsDesc)  + ") ENGINE = TinyLog"
        );
        PreparedStatement statement = connection.prepareStatement("insert into test.test_40 ("+ Joiner.on(",").join(fields) + ") values (" + Joiner.on(",").join(questions) + ")" );
        for (int j = 0; j < rowsNum; j++) {
            for (int i = 0; i < fieldsNum; i++) {
                statement.setInt(i +1, i + 100*j);
            }
            statement.addBatch();
        }
        statement.executeBatch();
        
        ResultSet rs = connection.createStatement().executeQuery("select * from test.test_40");
        while (rs.next()) {
            System.out.println("next");
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < fieldsNum; i++) {
                sb.append(rs.getInt(i+1)).append(";");
            }
            System.out.println(sb.toString());
        }
    }
```

**Comment by greysap** [comment]
Hello. Thank you for response.
I had tried batch insert of 30+ columns with Spring jdbcTemplate+driver and it works without errors.
So it is definitely not a JDBC driver issue.

**Comment by timorDevp** [comment]
> 

I'm also having this problem, can tell me how did you solve it, thank you
