### ISSUE TITLE
Failed to respond

### ISSUE THREAD

**Issue by rasmus93** [yandex/clickhouse-jdbc#122]
Sometime get such exception(when do select/insert/alter queries):
`
Caused by: org.apache.http.NoHttpResponseException: clickhouse2:8123 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:492)
        ... 26 more
`
Maybe, do know why it can happens? Wrong configuration of something else?
Thanks!

**Comment by shahvishal8464** [comment]
How did you resolve this problem? I am having the same issue while trying to connect over the network:

java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: localhost, port: 8123; localhost:8123 failed to respond

Caused by: org.apache.http.NoHttpResponseException: localhost:8123 failed to respond

**Comment by shahvishal8464** [comment]
I was able to solve the problem using port forwarding on my local machine. Following is the command that I used: **ssh -4 -L 8123:localhost:8123 remote-host**

**Comment by rasmus93** [comment]
Hi, I have solved it by setting keep-alive-timeout on clickhouse-server(clickhouse configuration file) to 70 seconds.

**Comment by xiaods** [comment]
you can check the 8123 port is live. curl http://localhost:8123/   it should be return "OK"

**Comment by joneshoway** [comment]
java.lang.NoSuchMethodError: ru.yandex.clickhouse.ClickHouseConnectionImpl.createClickHousePreparedStatement(Ljava/lang/String;)Lru/yandex/clickhouse/ClickHousePreparedStatement;
