### ISSUE TITLE
get colums error

### ISSUE THREAD

**Issue by liyongcun** [yandex/clickhouse-jdbc#167]
java.lang.NumberFormatException: For input string: "16)"
	at ru.yandex.clickhouse.response.ByteFragmentUtils.parseInt(ByteFragmentUtils.java:57) ~[clickhouse-jdbc-0.1.34.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseResultSet.getInt(ClickHouseResultSet.java:299) ~[clickhouse-jdbc-0.1.34.jar:na]
	at org.apache.commons.dbcp.DelegatingResultSet.getInt(DelegatingResultSet.java:225) ~[commons-dbcp-1.4.jar:1.4]
	at org.apache.ddlutils.platform.MetaDataColumnDescriptor.readColumn(MetaDataColumnDescriptor.java:123) ~[ddlutils-1.0.jar:1.0]
 this colum type is Nullable(Int16)

**Comment by serebrserg** [comment]
must be fixed in referenced PR
