### ISSUE TITLE
initTimeZone   ClickHouse exception, code: 1002

### ISSUE THREAD

**Issue by will0815** [yandex/clickhouse-jdbc#171]
at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:91)
	at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:75)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:58)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:50)
	at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:32)
	at java.sql.DriverManager.getConnection(DriverManager.java:571)
	at java.sql.DriverManager.getConnection(DriverManager.java:233)
	at com.kugou.loader.clickhouse.ClickhouseClient.<init>(ClickhouseClient.java:47)
	at com.kugou.loader.clickhouse.ClickhouseClient.<init>(ClickhouseClient.java:39)
	at com.kugou.loader.clickhouse.ClickhouseClientHolder.getClickhouseClient(ClickhouseClientHolder.java:49)
	at com.kugou.loader.clickhouse.ClickhouseClientHolder.main(ClickhouseClientHolder.java:76)
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002,

**Comment by harlinb** [comment]
+1
502 causing a runtime exception to be thrown when calling clickHouseDataSource.getConnection(user, password);

```
4862658 [main] WARN  ru.yandex.clickhouse.ClickHouseStatementImpl  - error while read compressed streamMagic is not correct: 105
Exception in thread "main" java.lang.RuntimeException: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: internal-clickhouse-sig-alb-prod-1134240367.us
-west-1.elb.amazonaws.com, port: 8443; <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

        at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:91)
        at ru.yandex.clickhouse.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:75)
        at ru.yandex.clickhouse.ClickHouseDriver.connect(ClickHouseDriver.java:58)
        at ru.yandex.clickhouse.ClickHouseDataSource.getConnection(ClickHouseDataSource.java:50)
        at com.opendns.stats.clickhouse.SigIngestor.go(SigIngestor.java:108)
        at com.opendns.stats.clickhouse.SigIngestor.main(SigIngestor.java:406)
Caused by: ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: internal-clickhouse-sig-alb-prod-1134240367.us-west-1.elb.amazonaws.com, port: 8443; <html
>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
</body>
</html>

        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:88)
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
        at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.getInputStream(ClickHouseStatementImpl.java:519)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:107)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:91)
        at ru.yandex.clickhouse.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:87)
        at ru.yandex.clickhouse.ClickHouseConnectionImpl.initTimeZone(ClickHouseConnectionImpl.java:86)
        ... 5 more
Caused by: java.lang.Throwable: <html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
```

**Comment by will0815** [comment]
Use Clickhouse-client -h  to check clickhouse-server is ok, 
my problem is because the server's remote connection policy,   resolved

**Comment by serebrserg** [comment]
As I see, it is more or less resolved.
I've tried to find out if the error is correct, but in my cases I've received other codes and quite errors with good messages.
If you haven't and you have a test case, please reopen and describe the setup.
