### ISSUE TITLE
ResultSet#next() calls past last element throw IOException

### ISSUE THREAD

**Issue by tkroman** [yandex/clickhouse-jdbc#175]
```
java.sql.SQLException: java.io.IOException: Attempted read on closed stream.
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:132)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.next(ClickHouseResultSet.java:139)
	at ru.yandex.clickhouse.integration.ClickHouseStatementImplTest.testSingleColumnResultSetMultipleHasNextPastLast(ClickHouseStatementImplTest.java:78)
Caused by: java.io.IOException: Attempted read on closed stream.
	at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:109)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:118)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.readNextBlock(ClickHouseLZ4Stream.java:82)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.checkNext(ClickHouseLZ4Stream.java:74)
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.read(ClickHouseLZ4Stream.java:50)
	at ru.yandex.clickhouse.response.StreamSplitter.readFromStream(StreamSplitter.java:88)
	at ru.yandex.clickhouse.response.StreamSplitter.next(StreamSplitter.java:50)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:115)
	... 35 more
```

**Comment by akonyaev90** [comment]
`Caused by: java.sql.SQLException: java.io.IOException: Attempted read on closed stream.
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:129) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseResultSet.next(ClickHouseResultSet.java:143) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.ivi.groot.agnes.executors.sources.JDBCExecutor.writeResponseINTSVFileAndReturnLineCount(JDBCExecutor.java:180) ~[classes/:na]
	at ru.ivi.groot.agnes.executors.sources.JDBCExecutor.execAndSaveInFile(JDBCExecutor.java:85) ~[classes/:na]
	at ru.ivi.groot.agnes.executors.sources.SourceService.executeAgnesJob(SourceService.java:40) ~[classes/:na]
	at ru.ivi.groot.agnes.orm.job.Job.lambda$executeSinkWithRetries$2(Job.java:334) ~[classes/:na]
	at com.github.rholder.retry.AttemptTimeLimiters$NoAttemptTimeLimit.call(AttemptTimeLimiters.java:78) ~[guava-retrying-2.0.0.jar:na]
	at com.github.rholder.retry.Retryer.call(Retryer.java:160) ~[guava-retrying-2.0.0.jar:na]
	... 63 common frames omitted
`

on 1.42 I caught this exception

**Comment by akonyaev90** [comment]
`Caused by: java.sql.SQLException: java.io.IOException: Attempted read on closed stream.
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:129) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseResultSet.next(ClickHouseResultSet.java:143) ~[clickhouse-jdbc-0.1.42.jar:na]
	at 	... 63 common frames omitted
Caused by: java.io.IOException: Attempted read on closed stream.
	at org.apache.http.conn.EofSensorInputStream.isReadAllowed(EofSensorInputStream.java:109) ~[httpclient-4.5.2.jar:4.5.2]
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:118) ~[httpclient-4.5.2.jar:4.5.2]
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.readNextBlock(ClickHouseLZ4Stream.java:82) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.checkNext(ClickHouseLZ4Stream.java:74) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseLZ4Stream.read(ClickHouseLZ4Stream.java:50) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.StreamSplitter.readFromStream(StreamSplitter.java:92) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.StreamSplitter.next(StreamSplitter.java:54) ~[clickhouse-jdbc-0.1.42.jar:na]
	at ru.yandex.clickhouse.response.ClickHouseResultSet.hasNext(ClickHouseResultSet.java:116) ~[clickhouse-jdbc-0.1.42.jar:na]
	... 70 common frames omitted`

**Comment by akonyaev90** [comment]
I have same bug on 0.1.42
