### ISSUE TITLE
Can't use JSONCompact formatter

### ISSUE THREAD

**Issue by dubcan** [yandex/clickhouse-jdbc#189]
Query:

```sql
 SELECT 1 FORMAT JSONCompact
```

Expected result:

```javascript
{
	"meta":
	[
		{
			"name": "1",
			"type": "UInt8"
		}
	],

	"data":
	[
		[1]
	],

	"rows": 1,

	"statistics":
	{
		"elapsed": 0.00002133,
		"rows_read": 1,
		"bytes_read": 1
	}
}
```

Result:

```
ru.yandex.clickhouse.except.ClickHouseUnknownException: ClickHouse exception, code: 1002, host: unknown, port: -1; 	[
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.getException(ClickHouseExceptionSpecifier.java:88)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:55)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:28)
	at ru.yandex.clickhouse.except.ClickHouseExceptionSpecifier.specify(ClickHouseExceptionSpecifier.java:32)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.checkValues(ClickHouseResultSet.java:155)
	at ru.yandex.clickhouse.response.ClickHouseResultSet.next(ClickHouseResultSet.java:137)

```

**Comment by dubcan** [comment]
Incorrect usage of library from my side

Details:
https://github.com/yandex/clickhouse-jdbc/issues/188
