### ISSUE TITLE
Support for JDBC 4.1 API IS_GENERATEDCOLUMN column

### ISSUE THREAD

**Issue by UkrZilla** [yandex/clickhouse-jdbc#73]
According to The JDBC 4.1 API method getColumns should support column IS_GENERATEDCOLUMN

Please add support

**Comment by serebrserg** [comment]
Merged to master. Will be in next release.

**Comment by mgrenonville** [comment]
Hi, I've just tried to use the 0.1.18 version with jdbc 4.1 api, it throws an exception : 
```
Caused by: java.lang.IllegalArgumentException: size mismatch, req: 23 got: 24
	at ru.yandex.clickhouse.response.ClickHouseResultBuilder.names(ClickHouseResultBuilder.java:45)
	at ru.yandex.clickhouse.response.ClickHouseResultBuilder.names(ClickHouseResultBuilder.java:33)
	at ru.yandex.clickhouse.ClickHouseDatabaseMetadata.getClickHouseResultBuilderForGetColumns(ClickHouseDatabaseMetadata.java:861)
	at ru.yandex.clickhouse.ClickHouseDatabaseMetadata.getColumns(ClickHouseDatabaseMetadata.java:781)
```

It seems that the commit https://github.com/yandex/clickhouse-jdbc/commit/222f2e42277c695404364f7dfa0857f2a32e8535 doesn't update the int parameter according to argument list : 
https://github.com/yandex/clickhouse-jdbc/commit/222f2e42277c695404364f7dfa0857f2a32e8535#diff-18748a52ce8effbf9e1216eef6f27da2L858 should be: `ClickHouseResultBuilder builder = ClickHouseResultBuilder.builder(24);`
